version: "3.8"

services:
    mysql:
        image: mysql:latest
        container_name: mysql-container
        environment:
            MYSQL_ROOT_PASSWORD: 12345
            MYSQL_DATABASE: granos_de_oro # Asegúrate de que la base de datos exista
        volumes:
            - mysql-data:/var/lib/mysql
        ports:
            - "3306:3306"

    laravel:
        image: gdo-production:latest # Tu imagen de Laravel
        container_name: laravel-container
        ports:
            - "8000:8000" # Cambia el puerto si es necesario
        depends_on:
            - mysql
        environment:
            DB_CONNECTION: mysql
            DB_HOST: mysql
            DB_PORT: 3306
            DB_DATABASE: granos_de_oro
            DB_USERNAME: root
            DB_PASSWORD: 12345

volumes:
    mysql-data:
        external: true
